//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Useful_FunctionsCsh.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string Горизонтальный_масштаб {
            get {
                return ((string)(this["Горизонтальный_масштаб"]));
            }
            set {
                this["Горизонтальный_масштаб"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AcceptReturn {
            get {
                return ((bool)(this["AcceptReturn"]));
            }
            set {
                this["AcceptReturn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string ВертикальныйМасштаб {
            get {
                return ((string)(this["ВертикальныйМасштаб"]));
            }
            set {
                this["ВертикальныйМасштаб"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string ВысотаТекстаПопера {
            get {
                return ((string)(this["ВысотаТекстаПопера"]));
            }
            set {
                this["ВысотаТекстаПопера"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5\r\n")]
        public string ВысотаТекстаЛегенды {
            get {
                return ((string)(this["ВысотаТекстаЛегенды"]));
            }
            set {
                this["ВысотаТекстаЛегенды"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ввод текстовых данных")]
        public string Enter_text_data {
            get {
                return ((string)(this["Enter_text_data"]));
            }
            set {
                this["Enter_text_data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.5")]
        public string ВысотаИмениПоперечника {
            get {
                return ((string)(this["ВысотаИмениПоперечника"]));
            }
            set {
                this["ВысотаИмениПоперечника"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.8")]
        public string Заглубление_код_120 {
            get {
                return ((string)(this["Заглубление_код_120"]));
            }
            set {
                this["Заглубление_код_120"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.70")]
        public string Заглубление_каб {
            get {
                return ((string)(this["Заглубление_каб"]));
            }
            set {
                this["Заглубление_каб"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.0")]
        public string Превышение_ЛЭП {
            get {
                return ((string)(this["Превышение_ЛЭП"]));
            }
            set {
                this["Превышение_ЛЭП"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public string Превышение_ВХ {
            get {
                return ((string)(this["Превышение_ВХ"]));
            }
            set {
                this["Превышение_ВХ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Создавать междопутья")]
        public string Создать_междопутья {
            get {
                return ((string)(this["Создать_междопутья"]));
            }
            set {
                this["Создать_междопутья"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39")]
        public string Слой_междопутий {
            get {
                return ((string)(this["Слой_междопутий"]));
            }
            set {
                this["Слой_междопутий"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.6")]
        public string Высота_междопутий {
            get {
                return ((string)(this["Высота_междопутий"]));
            }
            set {
                this["Высота_междопутий"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ATP")]
        public string Стиль_текста {
            get {
                return ((string)(this["Стиль_текста"]));
            }
            set {
                this["Стиль_текста"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Создавать точки на пересечениях при интерполяции")]
        public string СозданиеТочекНаПересечениях {
            get {
                return ((string)(this["СозданиеТочекНаПересечениях"]));
            }
            set {
                this["СозданиеТочекНаПересечениях"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool СоздаватьТочкиИнтерполяция {
            get {
                return ((bool)(this["СоздаватьТочкиИнтерполяция"]));
            }
            set {
                this["СоздаватьТочкиИнтерполяция"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Checked")]
        public global::System.Windows.Forms.CheckState ЧекСтэйт {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["ЧекСтэйт"]));
            }
            set {
                this["ЧекСтэйт"] = value;
            }
        }
    }
}
